// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Kendo.PlayGround.Domain.Entities;
using Kendo.PlayGround.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Kendo.PlayGround.Persistence.Configurations
{
    public partial class CustomerDetailsConfiguration : IEntityTypeConfiguration<CustomerDetails>
    {
        public void Configure(EntityTypeBuilder<CustomerDetails> entity)
        {
            entity.HasKey(e => e.CustomerDetailsID)
                .HasName("PK_CustomerDetails_CustomerDetailsID")
                .IsClustered(false);

            entity.Property(e => e.CreatedBy).HasDefaultValueSql("1");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("GETDATE()");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerDetails_CustomerID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomerDetails> entity);
    }
}
